name: Deploy Frontend to All VMs

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vm: [frontend_vm_0, frontend_vm_1]

    steps:
      - name: Set IP from Secret
        id: set-ip
        run: |
          if [ "${{ matrix.vm }}" == "frontend_vm_0" ]; then
            echo "IP=${{ secrets.FRONTEND_VM_0 }}" >> $GITHUB_OUTPUT
          else
            echo "IP=${{ secrets.FRONTEND_VM_1 }}" >> $GITHUB_OUTPUT
          fi

      - name: SSH and Deploy to ${{ matrix.vm }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ steps.set-ip.outputs.IP }}
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl stop apache2
            cd /home/azureuser/frontend
            git pull origin main
            sudo sed -i "s|localhost:5000|${{ secrets.BACKEND_VM }}:5000|g" src/main.jsx
            npm install
            npm run build
            sudo systemctl start apache2
