name: Deploy Frontend to All VMs

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vm: [frontend_vm_0, frontend_vm_1]

    steps:
      - name: Set IP from Secret
        id: set-ip
        run: |
          if [ "${{ matrix.vm }}" == "frontend_vm_0" ]; then
            echo "IP=${{ secrets.FRONTEND_VM_0 }}" >> $GITHUB_OUTPUT
          else
            echo "IP=${{ secrets.FRONTEND_VM_1 }}" >> $GITHUB_OUTPUT
          fi

      - name: SSH and Deploy to ${{ matrix.vm }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ steps.set-ip.outputs.IP }}
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo cd /home/azureuser/frontend
            sudo git pull origin main
            sudo npm install
            sudo npm run build
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/
            sudo systemctl restart apache2
